[[main]]
none = "none"

[[main]]
name = "About me"
pageRef = "about"
identifier = "kxx6werTLr"
weight = 9_999

[[main]]
name = "Projects"
pre = "blogger"
pageRef = "projects"
identifier = "UFOJqevVuQ"
weight = 9_999

[[main]]
pre = "github"
url = "https://github.com/fxd24/"
identifier = "y5oR5zmmaU"
weight = 9_999

[[main]]
pre = "linkedin"
url = "https://www.linkedin.com/in/grafda/"
identifier = "vV0IsIV1uB"
weight = 9_999

[[footer]]
none = "none"
